-- Usuario(__idUsuario__,nome,email,senha).
CREATE TABLE USUARIO (
	ID_USUARIO INT NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	SENHA VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID_USUARIO)
);

-- UsuarioPremium(__idUsuario__,num_cartao,cvv).
CREATE TABLE USUARIO_PREMIUM(
	ID_USUARIO INT NOT NULL,
	NUM_CARTAO INT(16) NOT NULL,
	CVV INT(3) NOT NULL,

	PRIMARY KEY(ID_USUARIO),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE ARTISTA(
	NOME_ARTISTA VARCHAR(255) NOT NULL,
	DATA_DE_FUNDACAO DATE,
	PRIMARY KEY(NOME_ARTISTA)
);

CREATE TABLE ALBUM(
	NOME_ARTISTA VARCHAR(255) NOT NULL,
	NOME_ALBUM VARCHAR(255) NOT NULL,
	DURACAO TIME NOT NULL,
	DATA_LANCAMENTO DATE,

	PRIMARY KEY(NOME_ARTISTA,NOME_ALBUM),
	FOREIGN KEY(NOME_ARTISTA) REFERENCES ARTISTA(NOME_ARTISTA)
);

CREATE TABLE MUSICA(
	NOME_ARTISTA VARCHAR(255) NOT NULL,
	NOME_ALBUM VARCHAR(255) NOT NULL,
	NOME_MUSICA VARCHAR(255) NOT NULL,
	DURACAO TIME NOT NULL,
	ORDEM INT,

	PRIMARY KEY(NOME_ARTISTA,NOME_ALBUM,NOME_MUSICA),
	FOREIGN KEY(NOME_ARTISTA,NOME_ALBUM) REFERENCES ALBUM(NOME_ARTISTA,NOME_ALBUM)
);

CREATE TABLE GENERO(
	NOME_GENERO VARCHAR(255) NOT NULL,

	PRIMARY KEY(NOME_GENERO)
);

CREATE TABLE PLAYLIST(
	ID_PLAYLIST INT NOT NULL,
	NOME VARCHAR(255) NOT NULL,

	PRIMARY KEY(ID_PLAYLIST)
);

CREATE TABLE MUSICA_SALVA(
	ID_MUSICA_SALVA VARCHAR(255) NOT NULL,

	PRIMARY KEY(ID_MUSICA_SALVA)
);






















