-- SegueUsuario(__idUsuario__,__idUsuario__).

-- Escuta(__idUsuario__,__nomeArtista__,__nomeAlbum__,__nomeMusica__,Data,Hora).

-- PlaylistContemMusicas(__idPlaylist__,__nomeArtista__,__nomeAlbum__,__nomeMusica__).

-- MusicaÉDoGenero(__nomeArtista__,__nomeAlbum__,__nomeMusica__,__nomeGenero__).

-- SegueArtista(__idUsuario__,__nomeArtista__).


CREATE TABLE SEGUE_USUARIO(
	ID_SEGUIDOR INT NOT NULL,
	ID_SEGUIDO INT NOT NULL,

	PRIMARY KEY(ID_SEGUIDOR,ID_SEGUIDO),
	FOREIGN KEY(ID_SEGUIDO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(ID_SEGUIDOR) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ESCUTA(
	ID_USUARIO INT NOT NULL,
	NOME_ARTISTA VARCHAR(255) NOT NULL,
	NOME_ALBUM VARCHAR(255) NOT NULL,
	NOME_MUSICA VARCHAR(255) NOT NULL,
	DATA DATE NOT NULL,
	HORA TIME NOT NULL,

	PRIMARY KEY(ID_USUARIO,NOME_ARTISTA,NOME_ALBUM,NOME_MUSICA,DATA,HORA),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(NOME_ARTISTA,NOME_ALBUM,NOME_MUSICA) REFERENCES MUSICA(NOME_ARTISTA,NOME_ALBUM,NOME_MUSICA) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PLAYLIST_CONTEM_MUSICA(
	ID_PLAYLIST INT NOT NULL,
	NOME_ARTISTA VARCHAR(255) NOT NULL,
	NOME_ALBUM VARCHAR(255) NOT NULL,
	NOME_MUSICA VARCHAR(255) NOT NULL,

	PRIMARY KEY(ID_PLAYLIST,NOME_ARTISTA,NOME_ALBUM,NOME_MUSICA),
	FOREIGN KEY(NOME_ARTISTA,NOME_ALBUM,NOME_MUSICA) REFERENCES MUSICA(NOME_ARTISTA,NOME_ALBUM,NOME_MUSICA) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(ID_PLAYLIST) REFERENCES PLAYLIST(ID_PLAYLIST) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MUSICA_SALVA_CONTEM_MUSICA(
	ID_MUSICA_SALVA INT NOT NULL,
	NOME_ARTISTA VARCHAR(100) NOT NULL,
	NOME_ALBUM VARCHAR(100) NOT NULL,
	NOME_MUSICA VARCHAR(100) NOT NULL,

	PRIMARY KEY(ID_MUSICA_SALVA,NOME_ARTISTA,NOME_ALBUM,NOME_MUSICA),
	FOREIGN KEY(NOME_ARTISTA,NOME_ALBUM,NOME_MUSICA) REFERENCES MUSICA(NOME_ARTISTA,NOME_ALBUM,NOME_MUSICA) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(ID_MUSICA_SALVA) REFERENCES MUSICA_SALVA(ID_MUSICA_SALVA) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MUSICA_EH_DO_GENERO(
	NOME_ARTISTA VARCHAR(100) NOT NULL,
	NOME_ALBUM VARCHAR(100) NOT NULL,
	NOME_MUSICA VARCHAR(100) NOT NULL,
	NOME_GENERO VARCHAR(100) NOT NULL,

	PRIMARY KEY(NOME_ARTISTA,NOME_ALBUM,NOME_MUSICA,NOME_GENERO),
	FOREIGN KEY(NOME_ARTISTA,NOME_ALBUM,NOME_MUSICA) REFERENCES MUSICA(NOME_ARTISTA,NOME_ALBUM,NOME_MUSICA) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(NOME_GENERO) REFERENCES GENERO(NOME_GENERO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SEGUE_ARTISTA(
	ID_USUARIO INT NOT NULL,
	NOME_ARTISTA VARCHAR(255) NOT NULL,

	PRIMARY KEY(ID_USUARIO,NOME_ARTISTA),
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(NOME_ARTISTA) REFERENCES ARTISTA(NOME_ARTISTA) ON DELETE CASCADE ON UPDATE CASCADE
);